In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make("FrozenLake-v0")

In [12]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size, action_space_size))
#print(q_table)

In [33]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.5

In [34]:
rewards_all_episodes = []

# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
        
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    
    rewards_all_episodes.append(rewards_current_episode)

# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes / 1000)
count = 1000
print("********Average reward per thousand episodes***********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

# Print updated Q-table
print("\n\n*****Q-table*****\n")
print(q_table)

********Average reward per thousand episodes***********

1000 :  0.6770000000000005
2000 :  0.6810000000000005
3000 :  0.6880000000000005
4000 :  0.7170000000000005
5000 :  0.6870000000000005
6000 :  0.6980000000000005
7000 :  0.6720000000000005
8000 :  0.6730000000000005
9000 :  0.6760000000000005
10000 :  0.6900000000000005


*****Q-table*****

[[0.59721343 0.52679756 0.53569528 0.54029816]
 [0.35082654 0.41592493 0.43003981 0.50406616]
 [0.41571767 0.39864677 0.39612867 0.46377148]
 [0.30169364 0.29411498 0.2923039  0.44626171]
 [0.6119333  0.34245155 0.36018228 0.26811398]
 [0.         0.         0.         0.        ]
 [0.28603783 0.1558198  0.17555712 0.12378555]
 [0.         0.         0.         0.        ]
 [0.40016239 0.44485969 0.35863554 0.63577035]
 [0.50667434 0.66575375 0.3351259  0.37032746]
 [0.64494028 0.3709644  0.29963404 0.25651213]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.50860504 0.53084444 0.78671804 0.437

In [23]:
for episode in range(3):
    state = env.reset()
    done = False
    print("********EPISODE ", episode+1, "*********\n\n\n\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done == True:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("******You reached the goal!********")
                time.sleep(3)
            else:
                print("******You fell through a hole!********")
                time.sleep(3)
            clear_output(wait=True)
            break
        
        state = new_state
        
env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG
******You fell through a hole!********
